# Data understanding

## 1. De dataset

In [1]:
import pandas as pd 
data = pd.read_csv("sap_storing_data_hu_project.csv")

/Users/jet/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (0,11,19,21,24,25,27,32,33,36,37,38,39,40,46,47,48,49,51,53,55,56,60,73,75,78,80,82,83,86,87,91,95,99,102,103,104,107,108,109,110,111,112,113,116,118,119,120,121,122,123,124,129) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
data.shape

(898526, 140)

Wat meteen opvalt is dat er een groot aantal kolommen zijn: namelijk 140. Dit zijn dus 140 variabelen die we mogelijk mee moeten nemen verder in ons project. Bij deze stap in het project willen we gaan kijken welke variabelen kansrijk zijn om bijvoorbeeld als feature- of targetvariabele aangewezen kunnen worden.

In eerste instantie maakt de dataset een redelijk rommelige indruk, dit komt waarschijnlijk door de lange en ietwat verwarrende namen van de kolommen en de verschillende datatypes waarin de waardes worden weergegeven. Het kan handig zijn om meer overzicht te creeëren binnen de dataset, door bijvoorbeeld kolommen een helderdere naam te geven. Gelukkig hebben we wel een legenda gekregen die ons uitlegt wat elke kolom in de dataset betekent.

In [3]:
data.head()

,Unnamed: 0,#stm_sap_meldnr,stm_mon_nr,stm_vl_post,stm_sap_meld_ddt,stm_sap_mon_meld_ddt,stm_sap_meldtekst_lang,stm_mon_begin_ddt,stm_sap_meldtekst,stm_mon_toelichting_trdl,...,stm_rapportage_maand,stm_rapportage_jaar,stm_x_bron_publ_dt,stm_x_bron_bestandsnaam,stm_x_bron_arch_dt,stm_x_actueel_ind,stm_x_run_id,stm_x_bk,stm_x_start_sessie_dt,stm_x_vervallen_ind
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,2014,07/05/2014 05:30:12,\\PUHAPS0149\Informatica_Prod\Inbox\Informatic...,31/12/9999 00:00:00,1,34415,3617016,07/05/2014 05:44:24,0
1,1,50053211,0.0,NaN,02/01/2006 09:00:00,02/01/2006 09:00:00,Logboeknr Geeltje : 49 Tijd: 0900 VL-Po...,NaN,Logboeknr Geeltje : 49 Tijd: 0900,NaN,...,1,2006,02/01/2006 09:00:00,\\PUHAPS0149\Informatica_Prod\Inbox\Informatic...,31/12/9999 00:00:00,1,1518,12704590,13/06/2013 13:37:52,0
2,2,50053213,48.0,GN,02/01/2006 12:35:00,02/01/2006 12:35:00,Logboeknr RBV : 48 Tijd: 1235 VL-Post: ...,02/01/2006 12:35:00,Logboeknr RBV : 48 Tijd: 1235 VL-P,NaN,...,1,2006,02/01/2006 12:35:00,\\PUHAPS0149\Informatica_Prod\Inbox\Informatic...,31/12/9999 00:00:00,1,1518,12704591,13/06/2013 13:37:52,0
3,3,50053214,72.0,ZL,02/01/2006 16:40:00,02/01/2006 16:40:00,Logboeknr RBV : 72 Tijd: 1640 VL-Post: ...,02/01/2006 16:40:00,Logboeknr RBV : 72 Tijd: 1640 VL-P,NaN,...,1,2006,02/01/2006 16:40:00,\\PUHAPS0149\Informatica_Prod\Inbox\Informatic...,31/12/9999 00:00:00,1,1518,12704592,13/06/2013 13:37:52,0
4,4,50053215,96.0,ZL,02/01/2006 22:30:00,02/01/2006 22:30:00,Logboeknr RBV : 96 Tijd: 2230 VL-Post: ...,02/01/2006 22:30:00,Logboeknr RBV : 96 Tijd: 2230 VL-P,NaN,...,1,2006,02/01/2006 22:30:00,\\PUHAPS0149\Informatica_Prod\Inbox\Informatic...,31/12/9999 00:00:00,1,1518,12704593,13/06/2013 13:37:52,0

## 2. Missing values

We willen onderzoeken hoeveel null waardes er zijn binnen de dataset. Op basis van het aantal null waardes kunnen we gaan beslissen welke kolommen te weinig waardes bevatten en dus niet bruikbaar zijn voor het project.

In [4]:
notnull = data.notnull().sum().sum()
null = data.isnull().sum().sum()
sum = 87436170 + 38357470
nulldata = (null/sum)*100
nulldata

30.4923762441408

Ongeveer 30% van de waardes in de dataset zijn leeg, als we uitzoeken welke kolommen dit vooral zijn kunnen we die kolommen droppen en zo het gehalte van lege waardes verminderen.

## 3. Correlatie

We willen de samenhang van de verschillende variabelen bekijken. Als variabelen sterk gecorreleert met elkaar zijn betekend dit dat er een verband te stellen is tussen die variabelen en ze dus mogelijk afhankelijk van elkaar fungeren.

In [5]:
data.corr()

,#stm_sap_meldnr,stm_mon_nr,stm_geo_mld_uit_functiepl,stm_equipm_nr_mld,stm_km_van_mld,stm_km_tot_mld,stm_prioriteit,stm_mon_nr__statuscode,stm_geo_gst_uit_functiepl,stm_equipm_nr_gst,...,stm_fh_duur,stm_reactie_duur,stm_status_sapnaarmon,stm_schadenr,stm_rapportage_maand,stm_rapportage_jaar,stm_x_actueel_ind,stm_x_run_id,stm_x_bk,stm_x_vervallen_ind
#stm_sap_meldnr,1.000000,-0.561259,0.224076,-0.203350,0.007434,-0.097676,-0.716977,0.154912,0.218851,-0.242909,...,0.065408,0.074173,-0.154282,0.000158,-0.023604,-0.176788,0.050593,-0.141028,0.157436,-0.254859
stm_mon_nr,-0.561259,1.000000,-0.207973,0.092692,-0.009408,0.114231,0.348891,-0.365677,-0.196783,0.140240,...,-0.059769,-0.000121,0.420675,-0.000888,0.011310,0.402291,-0.208674,0.334218,-0.344456,0.184754
stm_geo_mld_uit_functiepl,0.224076,-0.207973,1.000000,0.048381,0.044879,0.029848,-0.136484,0.019642,0.972265,0.009556,...,0.023062,0.030707,-0.040085,0.000203,-0.013678,-0.062358,0.056368,-0.056871,0.060315,-0.022844
stm_equipm_nr_mld,-0.203350,0.092692,0.048381,1.000000,0.008139,0.115466,0.228139,-0.182107,0.023451,0.906940,...,0.007824,0.069651,0.202643,-0.011145,-0.007791,0.353960,-0.112766,0.246999,-0.287830,0.039317
stm_km_van_mld,0.007434,-0.009408,0.044879,0.008139,1.000000,0.170240,-0.008822,0.007844,0.032288,0.008925,...,0.011923,0.001644,-0.000123,-0.000296,-0.000273,0.012869,-0.006359,0.003949,-0.009894,-0.009575
stm_km_tot_mld,-0.097676,0.114231,0.029848,0.115466,0.170240,1.000000,0.074985,-0.040486,0.057485,0.140130,...,0.015090,0.123904,0.070331,-0.001921,-0.015366,0.246908,-0.105544,0.235989,-0.189156,-0.000501
stm_prioriteit,-0.716977,0.348891,-0.136484,0.228139,-0.008822,0.074985,1.000000,-0.141229,-0.141094,0.232581,...,-0.006820,-0.036606,0.156048,-0.000799,0.020910,0.186586,-0.060460,0.129609,-0.169906,0.227123
stm_mon_nr__statuscode,0.154912,-0.365677,0.019642,-0.182107,0.007844,-0.040486,-0.141229,1.000000,0.032633,-0.169174,...,0.014891,-0.032052,-0.716439,0.003813,0.016695,-0.266935,0.391577,-0.308880,0.344565,-0.050238
stm_geo_gst_uit_functiepl,0.218851,-0.196783,0.972265,0.023451,0.032288,0.057485,-0.141094,0.032633,1.000000,0.010427,...,0.021116,0.051760,-0.045322,-0.004927,-0.018282,-0.061407,0.056778,-0.038975,0.072526,-0.021943
stm_equipm_nr_gst,-0.242909,0.140240,0.009556,0.906940,0.008925,0.140130,0.232581,-0.169174,0.010427,1.000000,...,0.007632,0.087383,0.198969,-0.010319,-0.012494,0.386720,-0.127220,0.298761,-0.312868,0.045243
stm_km_van_gst,0.046235,-0.048957,0.086167,-0.011530,0.175308,0.441738,-0.040236,0.031760,0.115230,0.007101,...,0.014012,0.036010,-0.031208,-0.000492,-0.002627,0.014543,0.001533,0.023961,-0.004437,-0.034997
stm_km_tot_gst,-0.010300,0.022103,0.050526,0.059147,0.113756,0.649900,0.005671,-0.044735,0.065788,0.076271,...,0.017142,0.108769,0.057300,-0.001304,-0.015324,0.178116,-0.075361,0.172577,-0.135497,-0.017344
stm_oorz_code,0.353319,-0.222087,0.203407,-0.035554,0.006770,-0.057227,-0.261187,0.071135,0.190661,-0.085141,...,0.028632,0.048740,-0.066523,-0.006706,-0.001783,-0.076196,0.061076,-0.071739,0.077945,-0.036135
stm_fh_status,-0.217210,0.015735,0.005319,-0.012667,0.000259,-0.016387,0.118920,0.064671,0.004360,-0.021873,...,-0.007453,-0.074735,-0.049024,-0.002641,0.007127,-0.070723,0.042796,-0.097821,0.085296,0.022311
stm_tao_telling_mutatie,-0.300278,0.328161,-0.135645,-0.036887,-0.007819,0.036375,0.129741,0.008948,-0.120814,-0.017404,...,-0.040127,-0.033873,0.245189,0.003370,-0.009052,-0.059709,-0.079148,-0.058906,0.091738,-0.148990
stm_contractgeb_mld,0.068555,-0.084193,0.040836,0.166860,0.003673,-0.017822,-0.028992,-0.011417,-0.003166,0.104258,...,0.006723,0.077324,-0.002923,-0.002884,0.000859,-0.010725,0.049853,-0.010284,0.007718,-0.001017
stm_contractgeb_gst,0.084121,-0.078367,0.002255,0.167610,0.008551,-0.006579,-0.055100,-0.004190,-0.031600,0.093696,...,0.012619,0.064285,-0.001154,-0.000824,-0.000691,-0.010663,0.048604,-0.013276,0.015890,-0.009830
stm_arbeid,0.041034,-0.086499,0.035203,-0.037223,-0.002273,-0.037462,0.013212,-0.001958,0.039756,-0.037258,...,0.076406,0.008211,-0.070516,-0.000944,-0.013399,-0.204738,0.091904,-0.133098,0.147542,-0.020759
stm_progfh_gw_lwd_datum,-0.262559,0.169060,0.001447,0.047060,0.010226,-0.001893,0.014111,-0.226526,0.004137,0.036173,...,-0.002555,0.109309,0.085690,NaN,-0.131344,0.912118,-0.081597,0.311197,0.499603,-0.056602
stm_progfh_gw_teller,0.085909,0.018158,-0.003545,0.002489,0.002068,0.071412,-0.177251,-0.014828,0.008593,0.044479,...,0.022379,-0.118857,0.010680,0.000294,-0.009897,0.165944,-0.004662,0.115846,-0.051607,-0.047484
stm_fh_duur,0.065408,-0.059769,0.023062,0.007824,0.011923,0.015090,-0.006820,0.014891,0.021116,0.007632,...,1.000000,0.001232,-0.021359,-0.000327,-0.002616,-0.007671,0.023105,-0.003208,0.006135,-0.016500
stm_reactie_duur,0.074173,-0.000121,0.030707,0.069651,0.001644,0.123904,-0.036606,-0.032052,0.051760,0.087383,...,0.001232,1.000000,0.008450,-0.001809,-0.032964,0.193329,-0.135324,0.384464,-0.204872,-0.020141
stm_status_sapnaarmon,-0.154282,0.420675,-0.040085,0.202643,-0.000123,0.070331,0.156048,-0.716439,-0.045322,0.198969,...,-0.021359,0.008450,1.000000,-0.002108,-0.010479,0.361165,-0.453820,0.272754,-0.339936,0.062680
stm_schadenr,0.000158,-0.000888,0.000203,-0.011145,-0.000296,-0.001921,-0.000799,0.003813,-0.004927,-0.010319,...,-0.000327,-0.001809,-0.002108,1.000000,0.001056,-0.002243,0.000729,-0.004815,0.005855,-0.000761
stm_rapportage_maand,-0.023604,0.011310,-0.013678,-0.007791,-0.000273,-0.015366,0.020910,0.016695,-0.018282,-0.012494,...,-0.002616,-0.032964,-0.010479,0.001056,1.000000,-0.065423,0.100486,-0.003613,-0.022455,0.009160
stm_rapportage_jaar,-0.176788,0.402291,-0.062358,0.353960,0.012869,0.246908,0.186586,-0.266935,-0.061407,0.386720,...,-0.007671,0.193329,0.361165,-0.002243,-0.065423,1.000000,-0.461142,0.705048,-0.820686,0.084283
stm_x_actueel_ind,0.050593,-0.208674,0.056368,-0.112766,-0.006359,-0.105544,-0.060460,0.391577,0.056778,-0.127220,...,0.023105,-0.135324,-0.453820,0.000729,0.100486,-0.461142,1.000000,-0.285377,0.516424,0.080888
stm_x_run_id,-0.141028,0.334218,-0.056871,0.246999,0.003949,0.235989,0.129609,-0.308880,-0.038975,0.298761,...,-0.003208,0.384464,0.272754,-0.004815,-0.003613,0.705048,-0.285377,1.000000,-0.596926,0.060551
stm_x_bk,0.157436,-0.344456,0.060315,-0.287830,-0.009894,-0.189156,-0.169906,0.344565,0.072526,-0.312868,...,0.006135,-0.204872,-0.339936,0.005855,-0.022455,-0.820686,0.516424,-0.596926,1.000000,-0.087543
stm_x_vervallen_ind,-0.254859,0.184754,-0.022844,0.039317,-0.009575,-0.000501,0.227123,-0.050238,-0.021943,0.045243,...,-0.016500,-0.020141,0.062680,-0.000761,0.009160,0.084283,0.080888,0.060551,-0.087543,1.000000

We tonen een klein overzicht van de variabelen die het sterkst gecorreleert zijn met elkaar. De variabelen die het sterkst met elkaar gecorreleert zijn, zoals bijvoorbeeld stm_progfh_gw_lwd_datum en stm_rapportage_jaar zeggen ons niet heel veel. Het is best logisch dat de prognose datum en het jaar waarin de rapportage gedaan is sterk met elkaar correleren. We zijn door deze correlaties dus niet perse veel wijzer geworden.

In [6]:
data.corr().unstack().sort_values().drop_duplicates()

stm_rapportage_jaar        stm_x_bk                    -0.820686
#stm_sap_meldnr            stm_prioriteit              -0.716977
stm_status_sapnaarmon      stm_mon_nr__statuscode      -0.716439
stm_x_bk                   stm_x_run_id                -0.596926
#stm_sap_meldnr            stm_mon_nr                  -0.561259
                                                          ...
stm_progfh_gw_lwd_datum    stm_rapportage_jaar          0.912118
stm_contractgeb_mld        stm_contractgeb_gst          0.965901
stm_geo_mld_uit_functiepl  stm_geo_gst_uit_functiepl    0.972265
#stm_sap_meldnr            #stm_sap_meldnr              1.000000
stm_arbeid                 stm_progfh_gw_lwd_datum           NaN
Length: 435, dtype: float64

## 4. Dubbele data

Er zijn een aantal kolommen die identieke waardes hebben en dus redundant zijn. Zo zien we hieronder dat er twee overbodige kolommen zijn die samen dezelfde informatie weergeven als stm_sap_meld_ddt. Ook zien we dat stm_geo_gst en stm_geo_mld precies dezelfde informatie bevatten. Dit is allemaal onnodige dubbele informatie die we in de volgende stap data preparation willen gaan verwijderen.

In [7]:
data[['stm_sap_meld_ddt', 'stm_sap_meldtijd', 'stm_sap_melddatum']]

           stm_sap_meld_ddt stm_sap_meldtijd stm_sap_melddatum
0                       NaN              NaN               NaN
1       02/01/2006 09:00:00         09:00:00        02/01/2006
2       02/01/2006 12:35:00         12:35:00        02/01/2006
3       02/01/2006 16:40:00         16:40:00        02/01/2006
4       02/01/2006 22:30:00         22:30:00        02/01/2006
...                     ...              ...               ...
898521  11/05/2013 08:06:00         08:06:00        11/05/2013
898522  11/05/2013 09:21:00         09:21:00        11/05/2013
898523  11/05/2013 09:21:00         09:21:00        11/05/2013
898524  20/08/2016 14:15:17         14:15:17        20/08/2016
898525  20/08/2016 14:15:17         14:15:17        20/08/2016

[898526 rows x 3 columns]

In [8]:
data[['stm_geo_gst', 'stm_geo_mld']]

       stm_geo_gst stm_geo_mld
0              NaN         NaN
1              624         624
2              201         201
3               25          25
4               12          12
...            ...         ...
898521         NaN         560
898522         468         468
898523         468         468
898524         102         102
898525         102         102

[898526 rows x 2 columns]

In de volgende stap data preparation gaan we de ontdekkingen verwerken en zo zorgen dat we de juiste data hebben om in ons model te gaan gebruiken.